name: "Sphinx: Render docs"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Install & setup pdm
      run: |
        python3 -m pip install pdm
        pdm sync -dG :all
        pdm info
    - name: Build docs
      run: |
        pdm run doc
    - name: Publish to GitHub Pages
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        name: html-docs
        path: build/html/
